### PR TITLE
Fix :as option in passwordless_for

### LINKED ISSUE #168: troubles upgrading to 1.0.0
first of all, congrats on releasing `1.0.0`! 🥳

I just tried upgrading [my app](https://github.com/yshmarov/insta2blog.com/pull/116) to 1.0.0, and faced a few challenges:

Now, `passwordless_for :users, at: '/', as: :auth`
generates:
Screenshot 2023-10-15 at 13 52 02

(it loses the `_`)

I remove the `as: :auth`, and change it to `passwordless_for :users, at: '/'`. Now the routes look like this:
Screenshot 2023-10-15 at 13 53 07

However now the tests are failing on `passwordless_sign_in(@user)`:

Screenshot 2023-10-15 at 13 53 54

### PR DESCRIPTION
**Pull request by mikker**
Fixes #168 

@yshmarov, @jpatters thank you for your reports. Could you try and see whether this fixes your problems? Thanks!

### CODE REVIEW

**Comment by yshmarov** [comment]
using `gem 'passwordless', github: 'mikker/passwordless', branch: 'fix-routes'`,
`passwordless_for :users, at: '/', as: :auth` gives me the following routes:

Screenshot 2023-10-22 at 18 59 58

=> looks good

However the tests do not pass. 

When calling`passwordless_sign_in(User.first)` I get the following errors:

- with`passwordless_for :users, at: '/', as: :auth`
Screenshot 2023-10-22 at 19 04 38

- with `passwordless_for :users, at: '/'`
Screenshot 2023-10-22 at 19 05 09

**Comment by mikker** [comment]
Hmm, that looks weird? Do you use the bundled mailer? It shouldn't use `send` in this branch: https://github.com/mikker/passwordless/blob/fix-routes/app/mailers/passwordless/mailer.rb#L15-L24

**Comment by mikker** [comment]
Did you get a chance to look more into this, @yshmarov

**Comment by jpatters** [comment]
I will try to make some time to test this later this week.

**Comment by yshmarov** [comment]
> Hmm, that looks weird? Do you use the bundled mailer? It shouldn't use `send` in this branch: https://github.com/mikker/passwordless/blob/fix-routes/app/mailers/passwordless/mailer.rb#L15-L24

It is failing on this line:
https://github.com/mikker/passwordless/blob/master/lib/passwordless/test_helpers.rb#L11

**Comment by mikker** [comment]
Of course, I didn't realise it was the test helpers. Fixed now, thanks!

**Pull request merged**
