### PR TITLE
Use timeout instead of expired at SessionsController#show

### LINKED ISSUE #38: Session Expires at is wrongly used
Noticed this while doing #37 

We are checking the session expiry time here - https://github.com/mikker/passwordless/blob/master/app/controllers/passwordless/sessions_controller.rb#L48 whereas it should use `timeout_at`. And, the `expires_at` should maybe used in the `authenticate_by_cookie` method instead. Correct me if I'm wrong, I may have misunderstood. If not, let me know, happy to send a PR.

### PR DESCRIPTION
**Pull request by fladson**
Fixes #38 

I didn't get the last part.

> the `expires_at` should maybe used in the `authenticate_by_cookie` method instead

If you can drop a line explaining it more I am happy to help.

### CODE REVIEW

**Comment by fladson** [comment]
Not sure why the `timeout_at` is not being updated

**Comment by mikker** [comment]
Hi @fladson! This is great – thanks!

What do you mean by _the timeout_at_ not being updated_?

**Comment by mikker** [comment]
💙💚💛💜❤️

I brought it home in the PR above. Thank you for your contribution!

**Comment by fladson** [comment]
Awesome, thanks for fixing it @mikker!

**Pull request closed without merging**
